"use client";

import { ArrowRight, Camera, Check, ChevronRight, FileUp, Globe2, Menu, MessageCircle, Search, Send, Upload, X } from "lucide-react";
import { useState } from "react";

const wa = "https://wa.me/447520688566?text=Hello%20China%20Parts%20Shop%2C%20I%20need%20help%20sourcing%20a%20spare%20part.";
const brands = ["dongfeng.png", "sinotruk.png", "foton.svg", "jac.png", "chery.png", "geely.png", "xcmg.svg", "zoomlion.svg", "sany.svg"];
const brandNames = ["Dongfeng", "Sinotruk", "Foton", "JAC", "Chery", "Geely", "XCMG", "Zoomlion", "SANY"];
const trending = ["Engine Parts", "Filters", "Brake Components", "Suspension", "Electrical", "Transmission", "Truck Parts", "Hydraulic Parts", "Crane Parts", "Machinery Parts", "Cooling System", "Body Parts"];
const bands = [
  ["Passenger & Automotive", "Everyday vehicle parts, identified against your requirement.", "Brake Pads|Filters|Alternators|Radiators|Suspension", "warm"],
  ["Truck & Commercial", "Reliable support for fleets, trucks, trailers and buses.", "Brake Chamber|Clutch|Air Dryer|Fuel Pump|Truck Filters", "green"],
  ["Heavy Equipment", "Technical sourcing for construction and lifting equipment.", "Hydraulic Pump|Excavator Filter|Undercarriage|Crane Components|Loader Parts", "lavender"],
] as const;

function Logo() { return <a href="#top" className="logo"><img src="/cps-logo.png" alt="CPS China Parts Shop"/><span><b>CHINAPARTS</b><small>YOUR SOURCING PARTNER</small></span></a>; }

export default function HomepageV2({ onVersionChange }: { onVersionChange: (version: "v1" | "v2") => void }) {
  const [menu, setMenu] = useState(false);
  const [rfq, setRfq] = useState(false);
  const [chat, setChat] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const openRfq = () => { setSubmitted(false); setRfq(true); };
  return <main className="v2" id="top">
    <header className="v2-header"><div className="v2-top wrap"><Logo/><div className="v2-search"><Search size={18}/><input aria-label="Search parts" placeholder="Search by part name, OEM number, vehicle or equipment"/><button onClick={openRfq}>Search</button></div><a className="v2-portal" href="#sourcing">Customer Portal</a><a className="v2-wa" href={wa} target="_blank"><MessageCircle size={16}/> WhatsApp</a><div className="v2-switch" aria-label="Design version"><button onClick={() => onVersionChange("v1")}>Premium</button><button className="active" onClick={() => onVersionChange("v2")}>Explore</button></div><button className="v2-menu" onClick={() => setMenu(true)} aria-label="Open menu"><Menu/></button></div><div className="v2-nav wrap"><b>Browse parts</b>{["Automotive", "Truck & Trailer", "Heavy Equipment", "Crane Parts", "Brands", "How It Works"].map((item) => <a key={item} href={item === "Brands" ? "#brands" : "#categories"}>{item}</a>)}<button onClick={openRfq}>Quick RFQ <ArrowRight size={14}/></button></div></header>
    {menu && <div className="v2-mobile-menu"><button onClick={() => setMenu(false)} aria-label="Close menu"><X/></button><Logo/><a href="#categories" onClick={() => setMenu(false)}>Browse parts <ChevronRight/></a><a href="#sourcing" onClick={() => setMenu(false)}>Easy sourcing <ChevronRight/></a><div className="v2-mobile-preview"><small>DESIGN PREVIEW</small><button onClick={() => onVersionChange("v1")}>Version 1 — Premium</button><button className="active" onClick={() => onVersionChange("v2")}>Version 2 — Explore</button></div><a href={wa} target="_blank"><MessageCircle/> WhatsApp Expert</a></div>}

    <section className="v2-hero"><div className="wrap v2-hero-grid"><aside><b>Explore by category</b>{["Passenger Vehicles", "SUVs & 4x4", "Truck & Trailer", "Bus Parts", "Heavy Equipment", "Crane Parts", "Construction Machinery", "Agricultural Machinery", "Industrial Components"].map(x => <button onClick={openRfq} key={x}>{x}<ChevronRight size={14}/></button>)}</aside><div className="v2-banner"><div><p>CHINA PARTS, CLEARER SOURCING</p><h1>Source the Right Chinese Part, <em>Faster.</em></h1><span>Search by vehicle, OEM number, part image, or upload your complete parts list.</span><div><button onClick={openRfq}>Find a Part <ArrowRight size={15}/></button><button onClick={openRfq} className="plain">Quick RFQ</button></div></div></div><aside className="v2-help"><Camera/><h2>Need Help Identifying a Part?</h2><p>Our parts team can work from the details you have.</p><button onClick={openRfq}><Upload/> Upload Photo</button><button onClick={openRfq}>Enter OEM <ChevronRight/></button><a href={wa} target="_blank"><MessageCircle/> WhatsApp Expert</a></aside></div></section>
    <section className="v2-actions wrap"><button onClick={openRfq}><Search/> Search by OEM <small>Find with a known number</small></button><button onClick={openRfq}><Camera/> Upload a Photo <small>For difficult-to-identify parts</small></button><button onClick={openRfq}><FileUp/> Send a Parts List <small>For bulk requirements</small></button><a href={wa} target="_blank"><MessageCircle/> Talk to an Expert <small>Fast human assistance</small></a></section>
    <section id="categories" className="v2-section wrap"><div className="v2-heading"><div><p>PRODUCT DISCOVERY</p><h2>Trending Categories</h2></div><button onClick={openRfq}>View all categories <ArrowRight size={15}/></button></div><div className="v2-trending">{trending.map((item, i) => <button onClick={openRfq} key={item}><span className={`trend-art t${i % 6}`}/><b>{item}</b></button>)}</div></section>
    <section className="v2-bands">{bands.map(([title, text, products, color]) => <div className={`v2-band ${color}`} key={title}><div className="wrap"><header><p>PARTS RANGE</p><h2>{title}</h2><span>{text}</span><button onClick={openRfq}>View All <ArrowRight size={15}/></button></header><div>{products.split("|").map((product, i) => <button onClick={openRfq} key={product}><span className={`part-mini pm${i}`}/><b>{product}</b><small>Request sourcing options</small></button>)}</div></div></div>)}</section>
    <section id="sourcing" className="v2-source wrap"><div className="v2-source-image"><div><p>TECHNICAL SUPPORT, HUMANLY DELIVERED</p><h2>Easy Parts<br/><em>Sourcing</em></h2><span>Send one requirement and let our team help identify the correct sourcing option.</span></div></div><form onSubmit={(event) => { event.preventDefault(); openRfq(); }}><p>START YOUR ENQUIRY</p><h2>Tell us what you need.</h2>{["Product / Part Name", "OEM Number", "Vehicle / Equipment", "Quantity", "Country"].map(label => <label key={label}>{label}<input placeholder={label === "OEM Number" ? "Optional if unknown" : `Enter ${label.toLowerCase()}`}/></label>)}<button>Get My Quote <ArrowRight size={15}/></button></form></section>
    <section className="v2-quality"><div className="wrap"><div className="v2-heading"><div><p>CHOOSE WITH CONFIDENCE</p><h2>Quality Options for Every Requirement</h2></div></div><div>{[["Genuine", "Maximum assurance for warranty-sensitive needs"], ["OE", "Original-equipment specification"], ["OEM", "Tier-one quality with practical value"], ["Aftermarket", "Flexible budgets and wide availability"], ["Replacement", "Functional alternatives for repairs"]].map(([title, copy], i) => <article key={title}><b>0{i + 1}</b><h3>{title}</h3><p>{copy}</p><Check/></article>)}</div></div></section>
    <section id="brands" className="v2-section wrap"><div className="v2-heading"><div><p>MAKES WE SUPPORT</p><h2>Chinese Brands, One Sourcing Channel</h2></div></div><div className="v2-brands">{brands.map((file, i) => <button onClick={openRfq} key={file}><img src={`/brands/${file}`} alt={`${brandNames[i]} logo`}/></button>)}</div></section>
    <section className="v2-trust"><div className="wrap">{["Verified sourcing process", "Technical part support", "Multiple quality options", "Global enquiries", "Bulk parts list support"].map((item, i) => <article key={item}><b>0{i + 1}</b><span>{item}</span></article>)}</div></section>
    <section className="v2-final"><div className="wrap"><p>CHINA PARTS SHOP</p><h2>One requirement. One clear route to the right part.</h2><button onClick={openRfq}>Request a Quote <ArrowRight size={15}/></button><a href={wa} target="_blank">WhatsApp our Team</a></div></section>
    <footer className="v2-footer"><div className="wrap"><Logo/><p>Professional sourcing support for Chinese automotive, commercial vehicle, heavy equipment, and machinery parts.</p><small>© 2026 China Parts Shop · Prototype demonstration</small></div></footer>
    <button className="v2-float" onClick={() => setChat(!chat)} aria-label="Open parts assistant"><MessageCircle/></button>
    {chat && <div className="v2-chat"><button onClick={() => setChat(false)}><X/></button><b>CPS Parts Assistant</b><p>Tell us the vehicle or equipment, and any OEM number or photo you have.</p><button onClick={openRfq}>Start a part enquiry <ArrowRight size={14}/></button></div>}
    {rfq && <div className="v2-overlay"><section><button className="v2-close" onClick={() => setRfq(false)}><X/></button>{submitted ? <div className="v2-success"><Check/><h2>Requirement received in demo mode.</h2><p>Your details have not been sent. This prototype demonstrates the proposed RFQ workflow.</p></div> : <form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><p>QUICK RFQ</p><h2>Send your requirement</h2>{["Full Name", "Company", "Email", "WhatsApp", "Part description / OEM number"].map(label => <label key={label}>{label}<input required={label === "Full Name" || label === "Email"} placeholder={label}/></label>)}<button>Submit RFQ <Send size={15}/></button></form>}</section></div>}
  </main>;
}
