"use client";
import { useEffect, useState } from "react";
import { ArrowRight, Bot, Camera, CarFront, Check, ChevronDown, ChevronRight, FileSpreadsheet, FileUp, Globe2, Hash, Menu, MessageCircle, Phone, Search, Send, Upload, X } from "lucide-react";

const wa = "https://wa.me/447520688566?text=Hello%20China%20Parts%20Shop%2C%20I%20need%20help%20sourcing%20a%20spare%20part.";
const categories = ["Passenger Vehicle Parts","SUV & 4x4 Parts","Truck & Trailer Parts","Bus Parts","Heavy Equipment Parts","Crane Parts","Construction Machinery","Agricultural Machinery","Industrial Components"];
const qualities = [["Genuine","Original vehicle / machine manufacturer boxed part.","Maximum assurance · Warranty-sensitive vehicles"],["OE","Original Equipment specification.","Factory specification · Strong value"],["OEM","Tier-1 component manufacturer.","High quality · Cost-effective premium sourcing"],["Aftermarket","Independent manufacturer product.","Wider availability · Flexible budgets"],["Replacement","Functional replacement alternative.","Budget-sensitive repairs · Practical availability"]];
const audience = ["Vehicle Owners","Workshops","Fleet Operators","Spare Parts Dealers","Equipment Companies","Procurement Teams"];
const faqs = ["What types of spare parts can I request?","Can I send a photo if I do not know the part number?","Can I submit an Excel parts list?","What is the difference between Genuine, OE, OEM, Aftermarket, and Replacement?","Can you assist with Chinese truck and heavy-equipment parts?","Do you serve customers outside China?","How do I receive a quotation?","Can businesses submit bulk requirements?"];

function Logo(){return <a href="#top" className="logo"><img src="/cps-logo.png" alt="CPS China Parts Shop"/><span><b>CHINAPARTS</b><small>YOUR SOURCING PARTNER</small></span></a>}
function Button({children,primary=true,onClick}:{children:React.ReactNode;primary?:boolean;onClick?:()=>void}){return <button onClick={onClick} className={primary?"btn primary":"btn"}>{children}<ArrowRight size={15}/></button>}

export default function Home(){
 const [menu,setMenu]=useState(false),[finder,setFinder]=useState("Search Part"),[chat,setChat]=useState(false),[faq,setFaq]=useState<number|null>(null),[rfq,setRfq]=useState(false),[step,setStep]=useState(1),[success,setSuccess]=useState(false),[language,setLanguage]=useState(false),[notice,setNotice]=useState(false),[chatStep,setChatStep]=useState(0);
 const openRfq=()=>{setRfq(true);setStep(1);setSuccess(false)};
 useEffect(()=>{window.scrollTo({left:0,top:window.scrollY})},[]);
 useEffect(()=>{
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
  const targets=Array.from(document.querySelectorAll<HTMLElement>(".section-title,.category,.source-grid button,.quality-grid article,.audience-grid button,.steps article,.brands>div button,.product-grid article,.rfq-copy,.rfq-open,.capability-image,.capability-content,.resources article,.faq>div,.final .wrap"));
  let previousY=window.scrollY;
  let direction:"up"|"down"="down";
  const onScroll=()=>{direction=window.scrollY<previousY?"up":"down";previousY=window.scrollY};
  targets.forEach((target)=>target.classList.add("scroll-reveal"));
  const observer=new IntersectionObserver((entries)=>entries.forEach((entry)=>{const target=entry.target as HTMLElement;if(entry.isIntersecting){target.dataset.revealDirection=direction;target.classList.add("is-visible")}else target.classList.remove("is-visible")}),{threshold:.12,rootMargin:"0px 0px -6% 0px"});
  targets.forEach((target)=>observer.observe(target));window.addEventListener("scroll",onScroll,{passive:true});
  return()=>{observer.disconnect();window.removeEventListener("scroll",onScroll);targets.forEach((target)=>target.classList.remove("scroll-reveal","is-visible"))};
 },[]);
 const chatReplies=["What type of vehicle or equipment is this for?","Do you know the brand or equipment make?","Do you have an OEM number or an image?","Great. I can prepare an enquiry for the parts team."];
 return <main id="top">
  <header><div className="nav wrap"><Logo/><nav>{["Parts","Vehicle & Equipment","Brands","How It Works","About","Resources"].map(x=><a href={'#'+x.toLowerCase().replaceAll(' ','-').replace('&','') } key={x}>{x}</a>)}</nav><div className="nav-actions"><div className="lang"><button onClick={()=>setLanguage(!language)}><Globe2 size={16}/> EN <ChevronDown size={14}/></button>{language&&<div className="drop"><b>English</b><span>العربية <em>Available in production</em></span><span>中文 <em>Available in production</em></span></div>}</div><a className="portal" href="#rfq">Customer Portal</a><a className="talk" href={wa} target="_blank"><MessageCircle size={16}/> Talk to Expert</a><Button onClick={openRfq}>Quick RFQ</Button><button className="hamb" onClick={()=>setMenu(true)} aria-label="Open navigation"><Menu/></button></div></div></header>
  {menu&&<div className="mobile-menu"><button className="close" onClick={()=>setMenu(false)}><X/></button><Logo/><div>{["Parts","Categories","Brands","Request a Part","Track Enquiry","About","Contact","Customer Portal"].map(x=><a onClick={()=>setMenu(false)} href={x==="Request a Part"?"#rfq":"#parts"} key={x}>{x}<ChevronRight/></a>)}</div><a href={wa} target="_blank" className="mobile-contact"><MessageCircle/> WhatsApp +44 7520 688566</a></div>}
  <section className="hero"><picture><source media="(max-width: 650px)" srcSet="/hero-industrial-mobile.png"/><img src="/hero-industrial.png" alt="Chinese SUV, heavy truck and crane in an industrial logistics yard" fetchPriority="high"/></picture><div className="hero-shade"/><div className="wrap hero-content"><p className="eyebrow">GLOBAL CHINESE PARTS SOURCING</p><h1>The Right Part.<br/><i>From the Right Source.</i></h1><p className="lead">Genuine, OE, OEM, aftermarket, and replacement parts for Chinese vehicles, trucks, heavy equipment, and machinery — sourced for customers worldwide.</p><div className="hero-buttons"><Button onClick={openRfq}>Request a Quote</Button><a className="btn" href={wa} target="_blank"><MessageCircle size={15}/> Enquire on WhatsApp</a><a className="browse" href="#parts">Browse Parts <ArrowRight size={15}/></a></div></div></section>
  <section className="finder wrap"><div className="finder-head"><span className="rule"/><div><p className="eyebrow">QUICK PART FINDER</p><h2>Find Your Part</h2></div></div><div className="tabs">{["Search Part","Upload Photo","OEM Number","Parts List"].map(x=><button key={x} onClick={()=>setFinder(x)} className={finder===x?"active":""}>{x}</button>)}</div><div className="finder-form"><div className="input"><Search size={18}/><input aria-label={finder} placeholder={finder==="Search Part"?"Search product, vehicle, brand, OEM or part number":finder==="OEM Number"?"Enter OEM / Part Number":finder==="Upload Photo"?"Upload part or nameplate image":"Upload Excel, CSV or PDF parts list"}/>{finder!=="Search Part"&&<Upload size={17}/>}</div><Button onClick={openRfq}>{finder==="Search Part"?"Find Part":"Request Part"}</Button></div></section>
  <section className="trust"><div className="wrap trust-grid">{[["01","Genuine · OE · OEM · Aftermarket","Multiple sourcing options"],["02","Worldwide Supply","Serving international customers"],["03","Technical Assistance","Part identification support"],["04","Fast RFQ Response","Structured quotation process"]].map(([n,t,d])=><div key={t}><b>{n}</b><span>{t}</span><small>{d}</small></div>)}</div></section>
  <SectionTitle id="parts" over="PRODUCT UNIVERSE" title="Parts Across Every Major Segment" text="From passenger vehicles to cranes and industrial machinery, source requirements through one specialist team."/><section className="wrap category-grid">{categories.map((x,i)=><button onClick={openRfq} className="category" key={x}><span className={'cat-art c'+i}></span><div><small>CHINESE PARTS</small><b>{x}</b><span>Explore sourcing options <ArrowRight size={15}/></span></div></button>)}</section>
  <section className="source wrap"><div><p className="eyebrow">SOURCING MADE SIMPLE</p><h2>How Do You Want to<br/>Find Your Part?</h2></div><div className="source-grid"><button onClick={openRfq}><b>01</b><Hash className="source-icon"/><h3>OEM / Part Number</h3><p>Know the number? Search directly.</p><ArrowRight/></button><button onClick={openRfq}><b>02</b><CarFront className="source-icon"/><h3>Vehicle Details</h3><p>Search by make, model, year, or chassis information.</p><ArrowRight/></button><button onClick={openRfq}><b>03</b><Camera className="source-icon"/><h3>Upload a Photo</h3><p>Send an image of the part or equipment nameplate.</p><ArrowRight/></button><button onClick={openRfq}><b>04</b><FileSpreadsheet className="source-icon"/><h3>Upload Parts List</h3><p>Perfect for workshops, fleets, wholesalers, and procurement teams.</p><ArrowRight/></button></div></section>
  <section className="quality"><div className="wrap"><SectionTitle over="CLEAR QUALITY OPTIONS" title="Choose the Right Part Quality" text="Different requirements need different sourcing options. Our team helps you choose based on fitment, quality, budget, and availability."/><div className="quality-grid">{qualities.map(([x,y,z],i)=><article key={x}><span className={'quality-mark qm'+i} aria-hidden="true"><i/><i/><i/></span><h3>{x}</h3><p>{y}</p><small>{z}</small></article>)}</div><button className="text-link" onClick={()=>setChat(true)}>Not sure which one you need? Ask a Parts Expert <ArrowRight size={16}/></button></div></section>
  <section className="wrap audience"><div><p className="eyebrow">B2B & BEYOND</p><h2>Built for More Than<br/>Individual Orders</h2><p>From one difficult-to-find component to a complete procurement list, China Parts Shop supports different sourcing requirements.</p><Button onClick={openRfq}>Upload Bulk Parts List</Button></div><div className="audience-grid">{audience.map(x=><button onClick={openRfq} key={x}>{x}<ArrowRight size={15}/></button>)}</div></section>
  <section id="how-it-works" className="process"><div className="wrap"><SectionTitle over="HOW IT WORKS" title="From Requirement to Delivery" text="A clear, technical and structured path from first enquiry to delivery."/><div className="steps">{[["Send Requirement","Search, upload a photo, enter OEM number, or send a parts list."],["Part Identification","Our team reviews the vehicle, equipment, and part details."],["Sourcing & Verification","The appropriate sourcing option is identified and checked."],["Receive Your Quote","Price, availability, and delivery details are provided."],["Order & Delivery","Once confirmed, the order moves into processing and delivery."]].map(([x,y],i)=><article key={x}><b>0{i+1}</b><span></span><h3>{x}</h3><p>{y}</p></article>)}</div></div></section>
  <section className="global"><div className="wrap global-inner"><div><p className="eyebrow">ONE PROFESSIONAL CHANNEL</p><h2>China Sourcing.<br/><i>Worldwide Support.</i></h2><p>China Parts Shop connects international customers with reliable Chinese automotive, machinery, and equipment parts through one professional sourcing channel.</p><b className="intl">International Enquiries Welcome</b></div><div className="globe"><div className="orb"></div>{["GCC","Middle East","Africa","Asia","Europe","International"].map((x,i)=><span className={'region r'+i} key={x}>{x}</span>)}</div></div></section>
  <section id="brands" className="brands wrap"><SectionTitle over="CATALOGUE / SOURCING EXAMPLES" title="Search by Brand or Equipment Make" text="We can help identify parts for a broad range of Chinese vehicles and equipment."/><div>{[{name:"Dongfeng",file:"dongfeng.png"},{name:"SINOTRUK",file:"sinotruk.png"},{name:"FOTON",file:"foton.svg"},{name:"JAC Motors",file:"jac.png"},{name:"Chery",file:"chery.png"},{name:"Geely",file:"geely.png"},{name:"XCMG",file:"xcmg.svg"},{name:"ZOOMLION",file:"zoomlion.svg"},{name:"SANY",file:"sany.svg"}].map((brand)=><button className="brand-tile" onClick={openRfq} key={brand.name}><img src={`/brands/${brand.file}`} alt={`${brand.name} logo`}/></button>)}</div><button className="text-link" onClick={openRfq}>View All Brands <ArrowRight size={16}/></button></section>
  <section className="products"><div className="wrap"><SectionTitle over="REQUEST-LED SOURCING" title="Popular Parts & Recent Requests" text="Availability and specification are confirmed through a structured quotation."/><div className="product-grid">{["Brake Rotor","Brake Pad Set","Air Filter","Hydraulic Filter","Alternator","Wheel Bearing"].map((x,i)=><article key={x}><div role="img" aria-label={x} className={'part p'+i}><img src="/parts-catalogue.png" alt=""/></div><small>{i>2?"HEAVY EQUIPMENT":"AUTOMOTIVE"}</small><h3>{x}</h3><p>Example ref: CPS-{1200+i*87}</p><span>Available on Request</span><button onClick={openRfq}>Request Quote <ArrowRight size={14}/></button></article>)}</div></div></section>
  <section id="rfq" className="rfq wrap"><div className="rfq-copy"><p className="eyebrow">QUICK RFQ</p><h2>Need a Part?<br/><i>Send the Requirement.</i></h2><p>You do not need to know every technical detail. Send us what you have — part name, OEM number, VIN, chassis details, image, nameplate, or parts list.</p><div><Check/> Technical identification support</div><div><Check/> Quality options matched to requirement</div></div><button className="rfq-open" onClick={openRfq}><span className="rfq-image" role="img" aria-label="Parts inspection and procurement workspace"></span><FileUp/><b>Start your RFQ</b><span>Send a requirement in under two minutes</span><ArrowRight/></button></section>
  <section className="whatsapp"><div className="wrap"><MessageCircle/><div><h2>Need a faster answer?</h2><p>Send your requirement directly to our parts team.</p></div><a className="btn primary" href={wa} target="_blank">Chat on WhatsApp <ArrowRight size={15}/></a></div></section>
  <section className="capability wrap"><div className="capability-image" role="img" aria-label="Automotive parts inspection in a warehouse"></div><div className="capability-content"><p className="eyebrow">WHY A SPECIALIST PARTNER</p><h2>Specialist Sourcing.<br/><i>Clearer Outcomes.</i></h2><p>One technical sourcing channel for requirements where correct identification, quality choice, and professional coordination matter.</p><div className="capability-points">{["Technical Part Identification","Bulk Requirement Handling","Multiple Quality Options","Structured International Sourcing"].map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3></article>)}</div></div></section>
  <section id="resources" className="resources"><div className="wrap"><SectionTitle over="PARTS KNOWLEDGE" title="Practical Guidance for Better Part Requests" text="Professional resources to make identifying and sourcing parts easier."/><div>{["Genuine vs OE vs OEM — What Is the Difference?","How to Find an OEM Part Number","What Information Helps Identify the Correct Spare Part?"].map((x,i)=><article className={'guide g'+i} key={x}><span>GUIDE 0{i+1}</span><h3>{x}</h3><button onClick={()=>alert("This guide is included as a demo preview.")}>Read guide <ArrowRight size={15}/></button></article>)}</div></div></section>
  <section className="faq wrap"><div><p className="eyebrow">COMMON QUESTIONS</p><h2>Parts Sourcing, Clearly Answered.</h2></div><div>{faqs.map((x,i)=><article key={x}><button onClick={()=>setFaq(faq===i?null:i)}>{x}<ChevronDown className={faq===i?"rot":""}/></button>{faq===i&&<p>{i===1?"Yes. Upload a clear image of the part or equipment nameplate and include any vehicle or equipment information you have.":"Send the details you have through our RFQ or WhatsApp. Our team will review the requirement and return with the relevant sourcing and quotation information."}</p>}</article>)}</div></section>
  <section className="final"><div className="wrap"><p className="eyebrow">CHINA PARTS SHOP</p><h2>One Requirement.<br/><i>One Sourcing Partner.</i></h2><p>Send your vehicle, machinery, or spare-parts requirement and let our team help identify the right sourcing option.</p><Button onClick={openRfq}>Request a Quote</Button><a className="btn" href={wa} target="_blank">WhatsApp Our Team <ArrowRight size={15}/></a><small>+44 7520 688566 &nbsp; · &nbsp; parts@chinapartsshop.com</small></div></section>
  <footer><div className="wrap footer-grid"><div><Logo/><p>Your China Spare Parts Sourcing Partner.</p><p>Professional sourcing support for Chinese automotive, commercial vehicle, heavy equipment, and machinery parts.</p></div>{[["Parts","Passenger Vehicles","Trucks & Trailers","Heavy Equipment","Crane Parts","Machinery Parts"],["Support","Request a Quote","Upload Parts List","Customer Portal","Contact","FAQs"],["Company","About","How It Works","Quality Options","Worldwide Service","Contact"]].map(([h,...links])=><details className="footer-links" key={h} open><summary>{h}<ChevronDown/></summary>{links.map(x=><a href="#top" key={x}>{x}</a>)}</details>)}<details className="footer-links contact-links" open><summary>Contact<ChevronDown/></summary><a href="tel:+447520688566">+44 7520 688566</a><a href="mailto:parts@chinapartsshop.com">parts@chinapartsshop.com</a><a href="#top">chinapartsshop.com</a><div className="social">in &nbsp; f &nbsp; ◎ &nbsp; ▶</div></details></div><div className="footbar wrap"><span>© 2026 China Parts Shop</span><div><button onClick={()=>setNotice(true)}>Prototype Information</button><a href="#top">Privacy</a><a href="#top">Terms</a><a href="#top">Cookies</a></div></div></footer>
  <div className="floaters"><a href={wa} target="_blank"><MessageCircle/> WhatsApp</a><button onClick={()=>setChat(true)}><Bot/> Chat</button></div><button className="mobile-chat-trigger" onClick={()=>setChat(true)} aria-label="Open parts assistant"><Bot/></button><div className="mobile-bar"><a href="tel:+447520688566"><Phone/>Call</a><a href={wa} target="_blank"><MessageCircle/>WhatsApp</a><button onClick={openRfq}><Send/>Quick RFQ</button></div>
  {rfq&&<div className="overlay"><section className="modal rfq-modal"><button className="close" onClick={()=>setRfq(false)}><X/></button>{success?<div className="success"><Check/><h2>Requirement received in demo mode.</h2><p>Your details have not been sent. This prototype demonstrates the proposed RFQ workflow.</p><Button onClick={()=>setRfq(false)}>Close</Button></div>:<><p className="eyebrow">QUICK RFQ · STEP {step} OF 5</p><h2>{["Contact","Vehicle / Equipment","Part Requirement","Uploads","Review your RFQ"][step-1]}</h2><div className="progress">{[1,2,3,4,5].map(x=><span className={x<=step?"on":""} key={x}/>)}</div><div className="fields">{step===1&&["Full Name","Company","Email","WhatsApp","Country"].map(x=><label key={x}>{x}<input placeholder={x}/></label>)}{step===2&&["Category","Brand","Model","Year","VIN / Chassis"].map(x=><label key={x}>{x}<input placeholder={x}/></label>)}{step===3&&["Part description","OEM number","Quantity","Quality preference"].map(x=><label key={x}>{x}<input placeholder={x}/></label>)}{step===4&&<button className="upload-box"><Upload/>Choose images, nameplate, Excel, CSV or PDF<small>Demo upload — no files leave your device</small></button>}{step===5&&<div className="review">Your requirement is ready for review.<br/><small>This is a non-submitting demo flow.</small></div>}</div><div className="modal-actions"><button className="back" onClick={()=>step>1&&setStep(step-1)}>Back</button><Button onClick={()=>step===5?setSuccess(true):setStep(step+1)}>{step===5?"Submit RFQ":"Continue"}</Button></div></>}</section></div>}
  {chat&&<div className="chat"><div className="chat-head"><div><Bot/><span><b>CPS Parts Assistant</b><small>Online · Demo Assistant</small></span></div><button onClick={()=>setChat(false)}><X/></button></div><div className="chat-body"><p className="bot-msg">Hello 👋<br/>I can help you find the right part or guide you to our team.</p>{chatStep>0&&<p className="bot-msg">{chatReplies[chatStep-1]}</p>}{chatStep===4?<Button onClick={()=>{setChat(false);openRfq()}}>Continue to RFQ</Button>:<div className="quick">{(chatStep===0?["Find a Part","Request a Quote","Search by OEM","Upload Part Photo","Upload Parts List","Track an Enquiry","Talk to an Expert"]:["Passenger Vehicle","Truck","Heavy Equipment","Crane","Machinery","Other"]).map(x=><button key={x} onClick={()=>x==="Talk to an Expert"?window.open(wa,"_blank"):x==="Request a Quote"?openRfq():setChatStep(Math.min(4,chatStep+1))}>{x}<ChevronRight size={14}/></button>)}</div>}</div></div>}
  {notice&&<div className="overlay"><section className="modal notice"><button className="close" onClick={()=>setNotice(false)}><X/></button><p className="eyebrow">PROTOTYPE INFORMATION</p><h2>Demonstration only</h2><p>This homepage is a visual and workflow demonstration. Product availability, brands, service regions, delivery estimates, and other operational information will be finalized with China Parts Shop before production launch.</p></section></div>}
 </main>
}
function SectionTitle({over,title,text,id}:{over:string,title:string,text:string,id?:string}){return <div className="section-title wrap" id={id}><p className="eyebrow">{over}</p><h2>{title}</h2><p>{text}</p></div>}
